import images from "./public/images/images";

const projectList = [
  {
    title: "Mytrams",
    des: "MyTRAMS is an all-in-one Travel Agency Management System built to simplify, automate, and centralize every core operation of a travel business. It seamlessly manages flight bookings, visa processing, hotel reservations, holiday packages, Umrah & Hajj services, customer records, financial transactions, supplier management, refunds, and detailed business reporting from one powerful platform. Featuring secure role-based access, intelligent automation, real-time analytics, and a user-friendly interface, MyTRAMS reduce operational costs, and confidently grow their business at any scale.",
    image: images.mytrams,
    category: "web",
    link: "https://mytrams.com",
  },
  {
    title: "Nested Matrix",
    des: "Nested Matrix is a modern restaurant automation system designed to streamline daily operations and maximize efficiency. It manages orders, billing, inventory, kitchen operations, staff workflows, customer management, and sales reporting in one centralized platform—helping restaurants operate faster, reduce errors, enhance customer experience, and make smarter, data-driven business decisions.",
    image: images.nested,
    category: "web",
    link: "https://nested-matrix.vercel.app/",
  },
  {
    title: "Property Managament ",
    des: "A modern property management software designed to simplify and automate property operations. It centralizes tenant management, rent collection, lease tracking, maintenance requests, expense management, financial reporting, and occupancy monitoring in one powerful platform—helping property owners and managers  reduce manual work.",
    image: images.Property,
    category: "web",
    link: "https://salamproperties.makeupcoders.com",
  },
  {
    title: "School HRM",
    des: "A comprehensive School HRM & Staff Management System built to simplify and automate school administration. It centralizes staff and teacher management, attendance tracking, announcements, departments, disciplinary records, leave management, emergency requests for staff and students, payroll processing, salary management, and detailed reports in one secure platform. With advanced role-based permissions, workflow automation, and real-time insights, the system helps educational institutions improve efficiency, ensure transparency, reduce administrative workload, and manage daily operations with confidence.",
    image: images.HRM,
    category: "web",
    link: "https://hrm.bisdsa.com",
  },
  {
    title: "Somiti Management",
    des: "A comprehensive Microfinance & Cooperative Management System designed to digitize and automate every aspect of microfinance operations. It efficiently manages member registration, savings, loans, installments, repayments, penalties, transactions, collections, withdrawals, accounting, branch operations, and detailed financial reports from a single centralized platform. With real-time analytics, secure role-based access, automated calculations, and comprehensive reporting, the system helps microfinance institutions improve transparency",
    image: images.SomitiManagemet,
    category: "web",
    link: "https://somiti.makeupcoders.com",
  },
  {
    title: "BISD (School Website)",
    des: "BISD School Website is a fully dynamic school website developed with a powerful content management system, allowing administrators to manage every section without coding. From home page content, announcements, news, events, notices, galleries, academic information, admissions, teacher and staff profiles, achievements, downloads, contact information, and all other website pages, everything can be updated through an intuitive admin panel. The platform is built with secure role-based access, SEO-friendly architecture, responsive design, and scalable performance, enabling schools to maintain a modern, professional, and easily manageable online presence",
    image: images.BISD,
    category: "web",
    link: "https://bisdsa.com/",
  },
  {
    title: "Visamind",
    des: "VisaMind is a comprehensive visa processing and application management platform designed to simplify every step of the visa journey. It enables users to search visa requirements, submit applications, upload documents, track application status in real time, manage appointments, download vouchers, and monitor every stage of the visa process through a single centralized system. The platform also includes dynamic country-wise visa requirements, document verification, payment management, notifications, reporting, role-based access control, and a powerful admin dashboard—helping travel agencies deliver faster, more transparent, and highly efficient visa services.",
    image: images.visamind,
    category: "web",
    link: "https://www.visamind.net",
  },
  {
    title: "Bereinnya",
    des: "Bereinnya is a comprehensive travel booking platform designed to simplify travel planning and reservations. Users can seamlessly book hotels, tour guides, vehicles, holiday packages, houseboats, and customized travel experiences through a single, user-friendly platform. Featuring real-time availability, secure online bookings, itinerary management, payment integration, role-based access, and an intuitive admin dashboard, Bereinnya helps travel businesses deliver exceptional customer experiences while efficiently managing bookings and operations from one centralized system.",
    image: images.Bereinnya,
    category: "web",
    link: "https://bereinnya.com",
  },
  {
    title: "Visamind",
    des: "VisaMind is a Bangladesh-based visa and immigration consultancy that helps individuals with tourist, student, work, and immigration visa applications for multiple countries.",
    image: images.visamind,
    category: "web",
    link: "https://www.visamind.net",
  },
  {
    title: "Ineventory Management",
    des: "A modern Inventory Management System designed to streamline stock management, stock in/out, product tracking, supplier management, categories, purchases, sales, transactions, and inventory reporting through one centralized platform.",
    image: images.Inventory,
    category: "web",
    link: "https://inventory.makeupcoders.com",
  },
  {
    title: "Atom(Learning Management System)",
    des: "Atom LMS is a modern Learning Management System that enables online course management, student enrollment, progress tracking, quizzes, certificates, and integrated eCommerce for selling books, courses, and digital learning resources through a single platform.",
    image: images.Atoms,
    category: "web",
    link: "http://atom.makeupcoders.com",
  },
  {
    title: "ChattalMart",
    des: "Chattalmart is a modern eCommerce platform for organic and natural foods, allowing customers to easily order pure honey, ghee, dried fish (Shutki), spices, chili, and other premium local products. With secure online ordering, easy product browsing, inventory management, and a seamless shopping experience, it brings trusted organic products directly to customers' doorsteps.",
    image: images.Chattalmart,
    category: "web",
    link: "https://chattalmart.com/",
  },
  {
    title: "Himasti Cosmetics",
    des: "Himasti is a premium skincare and cosmetics eCommerce platform featuring product catalogs, secure online shopping, order management, customer accounts, promotions, and a responsive user experience—making beauty shopping simple, secure, and convenient.",
    image: images.Himasti,
    category: "web",
    link: "https://www.himasti.com",
  },
  {
    title: "Savinger",
    des: "A comprehensive Savings & Microfinance Management System designed to digitize and automate cooperative and savings group operations. It manages members, savings, loans, installments, deposits, withdrawals, penalties, transactions, and financial reports through a secure, role-based platform—ensuring transparency, accuracy, and efficient financial management.",
    image: images.Savinger,
    category: "web",
    link: "https://savinger.makeupcoders.com",
  },
  {
    title: "Tech Solution Engineering",
    des: "TSE Engineers is a modern corporate engineering website designed to showcase engineering services, projects, technical expertise, company profile, certifications, and client solutions through a fully responsive and dynamic platform with an intuitive content management system.",
    image: images.TSE,
    category: "web",
    link: "https://tse-engineers.com/",
  },
  {
    title: "Nippon Bangladesh",
    des: "Nippon Bangladesh is a fully dynamic corporate website featuring service management, project portfolios, product showcases, news & events, inquiries, and role-based content management—built with a modern, responsive, and SEO-optimized architecture for efficient website administration.",
    image: images.Nippon,
    category: "web",
    link: "https://nippon-bangladesh.com/",
  },
  {
    title: "Foot Fitness",
    des: "We are on a mission to redefine fashion by blending style, quality, and craftsmanship into every garment we offer. We believe what you wear is an expression of your unique personality, and it reflects your aspirations.",
    image: images.footFitness,
    category: "web",
    link: "https://foot-finesse-alpha.vercel.app/",
  },
  {
    title: "Tramedy",
    des: "At TraMedi, you gain access to a full spectrum of medical services, ensuring that your entire journey is supported, comfortable, and stress-free at affordable prices",
    image: images.tramedi,
    category: "web",
    link: "https://tramedi.care/",
  },
  {
    title: "Single Vendor Ecommerce",
    des: "An online clothing store featuring premium cotton t-shirts and trendy apparel for men, women, and kids. With a modern design, easy navigation, and secure checkout, shopping fashion becomes simple and stylish.",
    image: images.ClothWeb,
    category: "web",
    link: "https://beautyessencebd.com/",
  },
  {
    title: "Religion Website",
    des: "Mettadhamma is a modern, fully dynamic Buddhist digital platform designed to share Dhamma teachings, articles, videos, events, publications, galleries, and community updates through an intuitive content management system. Featuring role-based administration, multilingual content management, responsive design, and SEO optimization, the platform makes spiritual knowledge accessible and easy to manage.",
    image: images.Metta,
    category: "web",
    link: "https://mettadhamma.com/",
  },
  {
    title: "Adsusu",
    des: "An micro investment website for the people who has lower saving.",
    image: images.adsusu,
    category: "web",
    // link: "https://mytrams.com",
  },
  {
    title: "CryptoPulse- a crypto exchange",
    des: "CryptoPulse is a next-gen crypto exchange platform offering advanced analytics, real-time market data, and secure trading. Discover hidden gems in the crypto world with powerful tools designed for smart investors.",
    image: images.CryptoWeb,
    category: "web",
    link: "https://urban-market-sl.vercel.app/",
  },
  {
    title: "Travelion",
    des: "Travelion is a powerful B2B and B2C travel sales platform designed to simplify travel bookings and business operations. It enables agencies and customers to manage flight tickets, hotel bookings, tour packages, and travel services through a seamless digital platform. With partner management, customer booking, pricing control, sales tracking, payment management, and real-time reporting, Travelion helps travel businesses scale efficiently and deliver a better booking experience.",
    image: images.travelion,
    category: "web",
    link: "https://travel-ion.com",
  },
  {
    title: "Pacific Cliff",
    des: "A delivery website frontend developed for an Australian client.",
    image: images.pacificCliff,
    category: "web",
    // link: "https://mytrams.com",
  },
  {
    title: "Sokol Sheba",
    des: "Sokol Sheba is a modern on-demand service marketplace platform designed to connect customers with trusted service providers. Users can easily discover and book various home, office, repair, maintenance, and lifestyle services through a seamless digital platform. With service management, provider management, online booking, scheduling, customer accounts, payments, and admin control, the platform simplifies service operations and delivers a convenient user experience",
    image: images.sokolseba,
    category: "web",
    link: "https://www.sokolsheba.xyz/",
  },
  {
    title: "Invoice Generator",
    des: "Invoice Generator is a lightweight and efficient web application that allows businesses to create, customize, and download professional invoices in seconds. It supports itemized billing, automatic calculations, tax handling, and PDF export—making invoicing fast, accurate, and hassle-free.",
    image: images.genAi,
    category: "web",
    link: "https://invoicegenius.makeupcoders.com",
  },
  {
    title: "Haque & Sons Engineering Technology",
    des: "A corporate website developed for Haque & Sons Engineering Technology, a Bangladesh-based elevator and escalator solutions company. The platform showcases their services including installation, modernization, maintenance, and repair, with a strong focus on safety, reliability, and engineering expertise.",
    image: images.haqueAndSons,
    category: "web",
    link: "https://www.haquensons.com/",
  },

  {
    title: "Chattogram Somiti Web",
    des: "A Welfare Management Website building by React and Nodejs",
    image: images.SomitiWeb,
    category: "web",
    link: "https://ctgsomitidmm.com/",
  },
  {
    title: "Easy Accounting",
    des: "Easy Accounting is a modern accounting platform built to simplify financial management for growing businesses. From single journal entries to automated ledgers, balance sheets, and real-time dashboards — it delivers clarity, speed, and control without the ERP complexity.",
    image: images.EasyAccounting,
    category: "web",
    link: "https://sohojhishab.makeupcoders.com/",
  },
  {
    title: "Super Admin Panel",
    des: "Custom Super admin panel designed and developed by us.",
    image: images.commonAdmin,
    category: "web",
    // link: "https://mytrams.com",
  },
  {
    title: "Admin Panel",
    des: "Custom admin panel designed and developed by us.",
    image: images.adminpanel,
    category: "web",
    // link: "https://mytrams.com",
  },
  {
    title: "Somiti Management App",
    des: "A community app built for Brihattar Chattagram Somiti, connecting members through messaging, profiles, and digital membership cards. It makes communication and management easier, smarter, and more organized",
    image: images.Somiti,
    category: "app",
    // link: "https://mytrams.com",
  },
  {
    title: "Booking App",
    des: "A smart booking app that lets users reserve flights, hotels, events, or services anytime, anywhere. With real-time availability and instant confirmation, managing reservations becomes seamless and hassle-free.",
    image: images.BookingApp,
    category: "app",
    // link: "https://mytrams.com",
  },

  {
    title: "Turf Management",
    des: "Football & Cricket Turf management app for managing their slots.",
    image: images.turfmngmnt,
    category: "app",
  },
  {
    title: "Audio App",
    des: "A sleek music app that lets you explore albums, discover bands, and enjoy your favorite tracks in one place. With a modern glass-style interface, your music journey feels fresh, immersive, and intuitive.",
    image: images.MusicApp,
    category: "app",
  },
  {
    title: "Retailer Info",
    des: "A retailer management android app for the dealer to manage his transaction.",
    image: images.retailerInfo,
    category: "app",
  },
  {
    title: "T-score",
    des: "Cricket & Football Live-Scores App.",
    image: images.Tscore,
    category: "app",
  },
  {
    title: "Coaching Management",
    des: "A smart coaching management app that tracks student enrollment, daily attendance, and fees in one place. With real-time updates on earnings and unpaid dues, it makes running your coaching center simple and organized..",
    image: images.ClassMaster,
    category: "app",
  },
  {
    title: "Telemedicine App",
    des: "A modern healthcare app that helps you find top doctors and hospitals, book appointments, and access telemedicine services instantly. From online consultations to hospital visits, manage your healthcare needs all in one place.",
    image: images.DoctorUi,
    category: "app",
  },
  {
    title: "Nijer Hisab",
    des: "A modern accounting app that helps you track expenses, manage income, and generate reports with ease.",
    image: images.nijerHisab,
    category: "app",
  },
  {
    title: "E-Commerce",
    des: "A single vendor e-commerce website UI.",
    image: images.ecommerceui,
    category: "uiux",
  },
  {
    title: "Hotel Reservation",
    des: "Multiple hotel reservation mobile app UI.",
    image: images.hotelui,
    category: "uiux",
  },
  {
    title: "NFT Website",
    des: "A eye-catching NFT website UI.",
    image: images.nftui,
    category: "uiux",
  },
  {
    title: "GEN Z",
    des: "A beautiful smart website by our UI/UX designer.",
    image: images.genzui,
    category: "uiux",
  },
  {
    title: "Golio",
    des: "A beautyful landing page UI.",
    image: images.golioui,
    category: "uiux",
  },
  {
    title: "Watchshop",
    des: "Mobile app UI for a single vendor e-commerce.",
    image: images.watchshopui,
    category: "uiux",
  },
  {
    title: "Software Company Logo",
    des: "Mobile app UI for a single vendor e-commerce.",
    image: images.SofSourceLogo,
    category: "uiux",
  },
  {
    title: "Doctor App Panel",
    des: "Mobile app UI for a telemedicine App.",
    image: images.DoctorUi,
    category: "uiux",
  },
  {
    title: "Logo Branding of Cooking",
    des: "E-Radhuni is a modern cooking and recipe-sharing platform where you can cook, learn, love, and share your culinary journey. With a bold red-and-black identity, it brings together food lovers in a vibrant digital community",
    image: images.radhuni,
    category: "uiux",
  },
  {
    title: "Streaming App Design",
    des: "Mobile app UI for a Video Streaming App.",
    image: images.MusicAppUi,
    category: "uiux",
  },
  {
    title: "Ux Agency UI ",
    des: "A creative UX/UI design agency that transforms ideas into stunning digital experiences. From wireframes to polished interfaces.",
    image: images.usAgenecy,
    category: "uiux",
  },
  {
    title: "Ecommerce Design",
    des: "Ecomere Design app UI for a Single Vendor.",
    image: images.ClothWeb,
    category: "uiux",
  },
  {
    title: "Music App Design",
    des: "Mobile app UI for a Music App.",
    image: images.MusicDesignUi,
    category: "uiux",
  },
];

export default projectList;
